version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "5000:5000"  # Expose a single port for all services
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Bind the NGINX config file
    networks:
      - my-app-network

  helloworld-service:
    build: ./helloworld-service
    networks:
      - my-app-network

  goodbye-service:
    build: ./goodbye-service
    networks:
      - my-app-network

networks:
  my-app-network:
    driver: bridge

